chore(deps): update arduino/setup-task action to v3 (#264)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [arduino/setup-task](https://redirect.github.com/arduino/setup-task) |
action | major | `v2` → `v3.0.0` |

---

### Release Notes

<details>
<summary>arduino/setup-task (arduino/setup-task)</summary>

###
[`v3.0.0`](https://redirect.github.com/arduino/setup-task/releases/tag/v3.0.0):
3.0.0

[Compare
Source](https://redirect.github.com/arduino/setup-task/compare/v2.0.0...v3.0.0)

#### Migration Guide

The version of the [**Node.js**](https://nodejs.org/en/about) runtime
used to execute the action has been updated from 20 to 24. This could be
a breaking change for certain GitHub Actions workflows.

If a workflow with dependency on the **arduino/setup-task** action uses
only [GitHub-hosted GitHub Actions
runners](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners),
no changes are required.

If the workflow uses a [self-hosted
runner](https://docs.github.com/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners),
the workflow run might fail after updating **arduino/setup-task**:

```text
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node24' is not supported, use 'docker', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load arduino/setup-task/v3/action.yml
```

This means an older runner version that does not provide Node.js 24.x is
installed on the runner machine. In this case, the runner must be
updated to a modern version with Node.js 24.x support prior to updating
the **arduino/setup-task** action in the affected workflow.

#### Changelog

##### Breaking

- Update Node.js runtime for action from 20 to 24
([#&#8203;1408](https://redirect.github.com/arduino/setup-task/issues/1408))

##### Enhancement

- Convert project to ECMAScript module format
([#&#8203;1410](https://redirect.github.com/arduino/setup-task/issues/1410))
- [Various dependency
updates](https://redirect.github.com/arduino/setup-task/pulls?q=merged%3A2024-02-07..2026-06-30+author%3Aapp%2Fdependabot)

#### Full Changeset

#### Contributors

- [@&#8203;tbjers](https://redirect.github.com/tbjers)

</details>

---

### Configuration

📅 **Schedule**: (in timezone America/Chicago)

- Branch creation
  - Only on Sunday and Saturday (`* * * * 0,6`)
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/levibostian/Wendy-iOS).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My4yNDIuMiIsInVwZGF0ZWRJblZlciI6IjQzLjI0Mi4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>